### ISSUE TITLE
Excessive CPU usage in Inbox

### ISSUE THREAD

**Issue by ezuk** [GaurangTandon/ProKeys#3] opened 2015-09-12 12:48 UTC
Hi there,

With ProKeys enabled, Google Inbox reaches 30-40% CPU usage on my system and becomes unresponsive after a few hours. All I need to do to reproduce this is open the Inbox tab and let it sit in the background.

This has also been noted here: https://www.reddit.com/r/chrome/comments/3a9jok/inbox_tab_eating_lots_of_cpu_on_desktop_but_not/ (the comments mention ProKeys).

Would be happy to send any traces needed. Thank you for this useful tool! :)

**Comment by GaurangTandon** [comment] 2015-09-12 17:38
Hello @ezuk, thanks for bringing this issue to my notice!

Actually, Google Inbox inserts dynamic iframes into the webpage, like when you hit the "Compose" (or that "+") button, it opens a Compose window and to listen to that window's keypresses and attach an event listener to it, I have to do this bit of [code](https://github.com/GaurangTandon/ProKeys/blob/master/js/detector.js#L1593). If you notice carefully, on line 1629, I have a `setTimeout` which repeats the function `checkNewIframe` every 1.5 second...

I will see what I can do. Perhaps, I will increase the limit to five seconds, or maybe just allow the user to set it. I will also experiment if gmail and inbox can be made to work *without* the need for such a timer.

If you have any other suggestion, do share it to me! :) (I will happily accept a pull request if you want to contribute)

PS: I will try my best to fix this. But, I won't be able to start before October 6, because my exams are here and I need to devote all my time to it. But, I promise once I get the time, I will do my best to resolve the issue! :-)

**Comment by ezuk** [comment] 2015-09-14 11:21
No problem, @GaurangTandon! I appreciate you getting back to me. I guess for now I will disable ProKeys, but I'll keep an eye out for any changes in this issue. Good luck with your exams! :)

**Comment by GaurangTandon** [comment] 2015-10-03 16:27
@ezuk Hello again! I had a holiday today so I devoted most of my time in fixing the problem. I thought I should pass an update here. Here are the changes:

1. I got rid of the repeated checking for iframes. Completely.
2. I attached one single handler to the document element, delegating `keydown` and `keypress` to `textarea`s, `input`s, and `[contenteditable]`s as needed.
3. Set `"all_frames: true"` in `manifest.json`, so that the content script works in all iframes within a page.

I have been testing this and it has yielded positive results :) So, hopefully, with few more tiny tit-bit edits, I will update ProKeys to version 2..6.0 by October 7 :D
  
Stay tuned for next update :)

**Comment by ezuk** [comment] 2015-10-03 18:23
Woot! Thank you, Guarang! Definitely staying tuned.

**Comment by GaurangTandon** [comment] 2015-10-06 12:15
@ezuk Hello once again!

I am so glad to inform you that I have successfully released ProKeys v2.6.0, (hopefully) fixing this issue, along with [many others](https://github.com/GaurangTandon/ProKeys#change-log) :D

Though, I had to give up my resolve of *not* using `setInterval` as some sites like Mailchimp insert iframes `after` the page had fully loaded (and that's why `all_frames: true` wasn't catching them). However, I used it only for these sites, and not for Gmail, Facebook, and others :)

I would be really thankful to you if you could try out ProKeys as you did before, and I hope Google Inbox wouldn't become unresponsive this time ;) [I would close the issue on your confirmation]

By the way, I was thinking of removing the case-sensitive requirement for snippet names (Currently, `abcd` and `ABCD` are not detected as same), as it may help users. Since you are a user as well, what do you think about this? Should I introduce this feature? Considering the fact that other power users may already be taking *advantage* of this system by having snippet names like `abcd`, `Abcd`, `abcD`, etc...

**Comment by ezuk** [comment] 2015-10-07 00:54
Hi Guarang!

I updated to 2.6.0, and for some reason, Gmail (not Inbox) started freezing
for me. Like, completely freezes dead, I have to actually close the tab to
make something happen. Do you think it might be related to ProKeys? Any way
to figure out the cause?

As for the case-sensitive requirement: IMHO, it's a good idea. The biggest
problem with using hotstrings (abbreviations) is actually remembering them.
Making them case insensitive forces users to create hotstrings that are
somewhat different (not IDK vs. idk), so I think it can make them easier to
remember.

Cheers,
Erez

**Comment by GaurangTandon** [comment] 2015-10-07 03:35
@ezuk That's very strange :( I just again checked both Gmail and Inbox and all their functionalities like compose, reply, and the Hangouts and Google+ widgets worked just fine. I used mathomania and the letter sample snippet and the processor usage in Task Manager remained fine. The console also had no logs whatsoever.

If this issue does affect all ProKeys users, then I am in for some serious trouble. I will ask some more people if this affects them as well. Perhaps, you could try disabling ProKeys and see the difference?

On a side note, Gmail *did crash* for me too, a few days back. However, not completely. Like, every time I opened my daily newsletter, and clicked any link inside it using Ctrl+Mouse click, Gmail froze entirely and I had to reload the page. This continued to haunt me for a day or so. So, I just hope your Gmail crash is just a temporary one too :)

**Comment by ezuk** [comment] 2015-10-07 10:55
I actually disabled ProKeys yesterday (after Gmail froze three times in
half an hour), and Gmail has been working kay since. So I think it might be
somehow related. The crash you're describing sounds just like what I
experienced -- did that happen with ProKeys installed, or just on its own?
Maybe it's another extension I have that's messing it up?

**Comment by GaurangTandon** [comment] 2015-10-07 13:35
@ezuk I have (unfortunately) been able to confirm that this crash happens only with ProKeys enabled. Still unfortunately, I **do not know** how this could have happened. It used to work fine all the time. I just checked and I have no mention of the word `click` in my content script, so there's no point of having an onclick listener attached anywhere. The only listeners that get attached in Gmail are `keydown` and `keypress`.

I am still investigating the cause of this problem. Because I want this problem gone. Because it wasn't there before. And it shouldn't be after.

Will post an update here (hopefully, of a fix :) )

**Comment by GaurangTandon** [comment] 2015-10-07 14:49
@ezuk I have nailed down the problem! It is that when you hold Ctrl or any key for some time, the `handleKeyDown` function gets called repeatedly (imho, since it's `on`keyDown and not `during`KeyDown, it **should** get called just once, but I don't know why it's implemented like that). And this function has enormous functionality underneath. So, that's what causes that tab to hang.

I am looking into throttling the calls. Let's see if it works.

**Comment by GaurangTandon** [comment] 2015-10-07 17:39
@ezuk Hey there! I have fixed the problem :D I will update it on the web in the next 17 hours (currently it's late night here and I am really tired). If you want to try it out now, I could send you, but Github won't let me attach zip file in this comment :(

Anyway, I fixed this problem by using debounce instead of throttle. It worked. I will later clean up some console.log calls and then compress and upload on the web for users :D

**Comment by ezuk** [comment] 2015-10-08 11:59
@GaurangTandon - awesome! Thank you for the updates! I'm replying 18 hours after you posted this -- does that mean the new version's out? :)

**Comment by GaurangTandon** [comment] 2015-10-08 13:24
Well, sorry to disappoint, I just noticed but debounce didn't quite fix the problem :( Anyway, I have nailed down the problem (by repeated testing) to this function:

    function handleKeyDown(e) {
		var keyCode = e.keyCode,
			node = e.target,
			// do not use `this` instead of node; `this` can be document iframe
			tgN = node.tagName;

		// document iframe
		if(!tgN) return;

		if(isGmail && isParent(node, "form"))
			// in Gmail, the subject and to address field
			// should not have any function.
			// These two fields have a "form" as their parent.
			// thus, we check if the node has a form as a parent
			// if it is, then it is a to or subject field node
			// and we will not perform operation (return false)
			return false;


		node = isContentEditable(node) ?
			(Placeholder.container || node)
			: node;

		tgN = node.tagName;

		// [Tab] key for tab spacing/placeholder shifting
		if(keyCode === 9 && !e.shiftKey && !e.ctrlKey){
			// in placeholder mode, tab => jumping of placeholders
			if(Placeholder.mode){
				e.stopPropagation();
				e.preventDefault();

				checkPlaceholderPresence(node, getText(node), Placeholder.fromIndex, Placeholder.toIndex, true);
			}
			// normal tab spacing if user specifies
			else if(tabKeySpace && tgN !== "INPUT"){
				e.preventDefault();
				e.stopPropagation();

				insertTabChar(node);
			}
			else resetPlaceholderVariables();
		}
		// snippet substitution hotkey
		else if(isSnippetSubstitutionKey(e, keyCode)){
			e.preventDefault();
			e.stopPropagation();
			checkSnippetPresence(node);
		}
		// pressing arrows breaks out of placeholder mode
		else if([37, 38, 39, 40].indexOf(keyCode) >  -1)
			resetPlaceholderVariables();
	}

I am still looking into the exact cause. The problem seems to occur **only** if you *first* click on a link inside an email, then press *any key* even for a split second. I will let you know the root cause, as such this is the first time in my life I am encountering such a cryptic bug.

**Comment by ezuk** [comment] 2015-10-08 13:50
Sure thing! No rush, and thank you!

**Comment by GaurangTandon** [comment] 2016-02-04 13:24
Hi @ezuk,

I am really sorry for the long delay (hopefully, you didn't uninstall ProKeys by now ;)) but I have finally figured out the culprit:

    function isContentEditable(node){
		var tgN = node && node.tagName,
			attr, parentCount, parent;

		// insanity checks first
		if(!node || tgN === "TEXTAREA" || tgN === "INPUT" || !node.getAttribute)
			return false;
		else{
			attr = node.getAttribute("contenteditable");

			// empty string to support <element contenteditable> markup
			if(attr === "" || attr === "true" || attr === "plaintext-only")
				return true;

			// important part below
			// note that if we introduce a snippet
			// then it generates <span> elements in contenteditable `div`s
			// but they don't have content-editable true attribute
			// so they fail the test, hence, here is a new check for them
			// search if their parents are contenteditable
			// but only do this if the current node is not a textarea
			// which we have checked above

			parentCount = 1; // only two parents allowed
			parent = node;

			do{
				parent = parent.parentNode;
				parentCount++;

				if(!parent) return false;
				if(isContentEditable(parent)) return true; // recursive call here
			}while(parentCount <= 2);

			return false;
		}
	}

This function was recursive - with a **non ending condition**; so it went on and on endlessly until it reached the top level element. 

I have fixed the bug in my local PC version. I will release the 2.8.0 update soon which implements this fix :)

**Comment by ezuk** [comment] 2016-02-04 20:15
Woot! Thank you, and thanks for the persistence! :)

**Comment by GaurangTandon** [comment] 2016-03-23 15:07
Hello,
I have been working hard for the new version all this time, and I am close to what I can call a 95% complete version :) But, this time, before I release to the public, I would like to ask you to please just test it out once. By testing I mean, to only install this extension[1] and use it as you would use ProKeys in a normal scenario. No extra effort is required. If possible, try replicating the bug you got earlier. You've been very helpful from the beginning, and possibly, you can give this one, final and most important help to me as well :D

I hope to get some good results after about a week of usage[2] :D

[1] - installing the [zip file](https://github.com/GaurangTandon/ProKeys/files/186243/prokeys.zip) is simple. Unzip it, go to chrome://extensions, check the "Developer mode" checkbox at the top right, select Load Unpacked extensions, and select this extension's folder.
[2] - do not worry about the snippets you create while using this test version, you can always use the "Import" button I provided there to restore the snippets back to the public ProKeys version when you install it after I upload it publically after this test.

Thank you so much! :)

**Comment by ezuk** [comment] 2016-03-23 18:55
Sure thing! I have it set up now, and it installed okay; I use Inbox, and
it'll take me a few days before I can really tell you whether or not I'm
experiencing any performance impact. I'll let you know in a week?

**Comment by GaurangTandon** [comment] 2016-03-24 02:52
That's great! Thank you! One more thing, the "Settings" page is unfinished so it will not work and using it (to change hotkeys, auto-inserts, etc.) might corrupt the data forcing a reinstall, so please be careful :)

**Comment by ezuk** [comment] 2016-03-25 16:34
Will do!

**Comment by ezuk** [comment] 2016-04-01 08:57
Hi there,

Just looping back to say that so far, so good! Having the extension
installed doesn't seem to be slowing down anything on my system. :)

**Comment by GaurangTandon** [comment] 2016-04-01 09:00
Wow! That's really awesome! Thanks for confirming! I am so glad I finally
fixed the issue :D I have been working on various small but useful features
and will hopefully publish the latest 3.0.0 version within a week :)

**Comment by ezuk** [comment] 2016-04-01 09:43
Sounds good, happy to help ;)

**Closed** 2016-04-04 11:56 UTC
Labels: enhancement

**Comment by GaurangTandon** [comment] 2016-05-27 10:36
I have published the v3.0.0 version today. Please have a look! https://chrome.google.com/webstore/detail/ekfnbpgmmeahnnlpjibofkobpdkifapn Thanks! :D
